api_platform:
    swagger:
        api_keys:
            JWT:
                name: Authprization
                type: header

    # title: Hello API Platform
    # version: 1.0.0
    # defaults:
    #     stateless: true
    #     cache_headers:
    #         vary: ['Content-Type', 'Authorization', 'Origin']
