api_platform:
    swagger:
        api_keys:
            JWT:
                name: Authprization
                type: header
    # enable_nelmio_api_doc: true
    # nelmio_api_doc:
    # sandbox:
    #     accept_type: 'application/json'
    #     body_format:
    #     # formats: ['json']
    #     default_format: 'json'
    #     request_format:
    #     formats:
    #         json: 'application/json'
    # oauth:
    #     authorizationUrl: /signup

    # title: Hello API Platform
    # version: 1.0.0
    # defaults:
    #     stateless: true
    #     cache_headers:
    #         vary: ['Content-Type', 'Authorization', 'Origin']
