name: API Platform Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.43
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: symfony_api
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env .env.test

      - name: Update DATABASE_URL env var
        run: sed -i 's/DATABASE_URL=.*/DATABASE_URL="mysql:\/\/root:@127.0.0.1:3306\/symfony_api?serverVersion=8.0.43"/' .env.test

      - name: Generate keypair
        run: php bin/console lexik:jwt:generate-keypair

      - name: Create database
        run: php bin/console doctrine:database:create --env=test

      - name: Create migrations
      run: php bin/console make:migration

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --env=test -n

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests
        env:
          KERNEL_CLASS: App\Kernel
          APP_ENV: test